name: "Prune Old Releases"

on:
  workflow_dispatch:

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    name: "prune old releases"
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          fetch-depth: 0
      - uses: actions/delete-package-versions@a31a43afa6c2d3afdf8b5f1e311b2dc75585932e # tag=v3
        with:
          min-versions-to-keep: 200
