name: Build and upload charts
  env:
    REPO_URL: ${{ secrets.REPO_URL }}
    USER: ${{ secrets.USER }}
    PASS: ${{ secrets.PASS }}

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build_and_upload.sh